# Generated by Django 5.2.8 on 2025-11-25 17:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_case_title_alter_case_initial_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In progress'), ('ready_for_documents', 'Ready for documents'), ('documents_generated', 'Documents generated')], default='draft', max_length=64),
        ),
        migrations.CreateModel(
            name='FollowupQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('code', models.CharField(blank=True, max_length=128, null=True)),
                ('text', models.TextField()),
                ('target_document_types', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('answered', 'Answered'), ('skipped', 'Skipped')], default='pending', max_length=32)),
                ('answer_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followup_questions', to='cases.case')),
            ],
            options={
                'verbose_name': 'Follow-up question',
                'verbose_name_plural': 'Follow-up questions',
                'ordering': ['order_index', 'created_at'],
            },
        ),
    ]
