# Generated by Django 5.2.8 on 2025-11-28 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_alter_case_status_followupquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In progress'), ('ready_for_documents', 'Ready for documents'), ('documents_generated', 'Documents generated'), ('approved', 'Approved')], default='draft', max_length=64),
        ),
    ]
