# Generated by Django 5.2.8 on 2025-11-28 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_alter_case_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='confluence_space_key',
            field=models.CharField(blank=True, help_text='Ключ выбранного пространства Confluence (например, PROD-BANK)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='confluence_space_name',
            field=models.CharField(blank=True, help_text='Человекочитаемое имя пространства Confluence', max_length=255, null=True),
        ),
    ]
