# Generated by Django 5.2.8 on 2025-11-28 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_case_confluence_space_key_case_confluence_space_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='confluence_page_id',
            field=models.CharField(blank=True, help_text='ID созданной страницы в Confluence', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='confluence_page_url',
            field=models.URLField(blank=True, help_text='URL созданной страницы в Confluence', null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='confluence_space_key',
            field=models.CharField(blank=True, help_text='Ключ пространства Confluence (например CRP)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='confluence_space_name',
            field=models.CharField(blank=True, help_text='Отображаемое имя пространства Confluence', max_length=255, null=True),
        ),
    ]
