# Generated by Django 5.2.8 on 2025-11-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatsession',
            old_name='metadata',
            new_name='initial_answers',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='case',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='is_active',
        ),
        migrations.AddField(
            model_name='chatsession',
            name='project_name',
            field=models.CharField(blank=True, help_text='Название проекта или идеи, заданное при создании сессии', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='requirements_draft',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='status',
            field=models.CharField(choices=[('interview', 'Interview'), ('finished', 'Finished')], default='interview', max_length=20),
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
