# Generated by Django 5.2.8 on 2025-11-25 14:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
        ('chat', '0002_rename_metadata_chatsession_initial_answers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatsession',
            old_name='initial_answers',
            new_name='metadata',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='project_name',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='requirements_draft',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='status',
        ),
        migrations.AddField(
            model_name='chatsession',
            name='case',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='cases.case'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatsession',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=16)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatsession')),
            ],
        ),
    ]
