# Generated by Django 5.2.8 on 2025-11-25 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_rename_initial_answers_chatsession_metadata_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsession',
            name='case',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='ChatSession',
        ),
    ]
