# Generated by Django 5.2.8 on 2025-11-25 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='case',
        ),
        migrations.RemoveField(
            model_name='document',
            name='document_type',
        ),
        migrations.RemoveField(
            model_name='requirementtable',
            name='document',
        ),
        migrations.RemoveField(
            model_name='requirementrow',
            name='table',
        ),
        migrations.RemoveField(
            model_name='requirementtable',
            name='case',
        ),
        migrations.DeleteModel(
            name='DocumentType',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='RequirementRow',
        ),
        migrations.DeleteModel(
            name='RequirementTable',
        ),
    ]
