# Generated by Django 5.2.8 on 2025-11-26 14:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0003_alter_case_status_followupquestion'),
        ('documents', '0002_remove_document_case_remove_document_document_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_type', models.CharField(choices=[('scope', 'Vision / Product Vision'), ('use_case', 'Use Case')], help_text='Тип документа (scope, use_case и т.д.).', max_length=50)),
                ('title', models.CharField(help_text='Заголовок документа (может быть сгенерирован из кейса).', max_length=255)),
                ('content', models.TextField(help_text='Текст документа (Markdown или обычный текст).')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved_by_ba', 'Approved by BA'), ('rejected_by_ba', 'Rejected by BA')], default='draft', help_text='Статус документа (draft/approved/rejected).', max_length=50)),
                ('llm_model', models.CharField(blank=True, help_text='Название модели, которая сгенерировала документ (например, gpt-4.1-mini).', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(help_text='Кейс, для которого сгенерирован документ.', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='cases.case')),
            ],
            options={
                'ordering': ['doc_type'],
                'unique_together': {('case', 'doc_type')},
            },
        ),
    ]
