# Generated by Django 5.2.8 on 2025-11-27 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generateddocument',
            name='structured_data',
            field=models.JSONField(blank=True, help_text='Структурированные данные документа (JSON по схеме артефакта).', null=True),
        ),
        migrations.AlterField(
            model_name='generateddocument',
            name='content',
            field=models.TextField(help_text='Текст документа (Markdown/текст), полученный из structured_data (рендер).'),
        ),
        migrations.AlterField(
            model_name='generateddocument',
            name='doc_type',
            field=models.CharField(choices=[('scope', 'Vision / Product Vision')], help_text='Тип документа (scope, ...).', max_length=50),
        ),
        migrations.AlterField(
            model_name='generateddocument',
            name='llm_model',
            field=models.CharField(blank=True, help_text='Модель, которая сгенерировала документ (например, gpt-5).', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='generateddocument',
            name='title',
            field=models.CharField(help_text='Заголовок документа (обычно берётся из structured_data.title).', max_length=255),
        ),
    ]
