# Generated by Django 5.2.8 on 2025-11-27 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_generateddocument_structured_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generateddocument',
            name='doc_type',
            field=models.CharField(choices=[('scope', 'Vision / Product Vision'), ('vision', 'Scope (Solution Boundaries)')], help_text='Тип документа (scope, ...).', max_length=50),
        ),
    ]
