# Generated by Django 5.2.8 on 2025-11-27 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_alter_case_status_followupquestion'),
        ('documents', '0005_alter_generateddocument_doc_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='generateddocument',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generateddocument',
            name='generation_status',
            field=models.CharField(choices=[('ready', 'Ready'), ('generating', 'Generating'), ('failed', 'Failed')], default='ready', max_length=20),
        ),
        migrations.AddField(
            model_name='generateddocument',
            name='prompt_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='generateddocument',
            name='prompt_version',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='generateddocument',
            name='source_snapshot_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='generateddocument',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='cases.case'),
        ),
        migrations.AlterField(
            model_name='generateddocument',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='generateddocument',
            name='doc_type',
            field=models.CharField(choices=[('vision', 'Vision / Product Vision'), ('scope', 'Scope (Solution Boundaries)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='generateddocument',
            name='llm_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='generateddocument',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('approved_by_ba', 'Approved by BA'), ('rejected_by_ba', 'Rejected by BA')], default='draft', max_length=50),
        ),
        migrations.AlterField(
            model_name='generateddocument',
            name='structured_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generateddocument',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
