# Generated by Django 5.2.8 on 2025-11-27 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_alter_case_status_followupquestion'),
        ('documents', '0006_generateddocument_error_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generateddocument',
            name='docx_file',
            field=models.FileField(blank=True, help_text='Сгенерированный DOCX файл (экспорт).', null=True, upload_to='generated_docs/'),
        ),
        migrations.AddField(
            model_name='generateddocument',
            name='docx_generated_at',
            field=models.DateTimeField(blank=True, help_text='Когда был сгенерирован DOCX.', null=True),
        ),
        migrations.AlterField(
            model_name='generateddocument',
            name='case',
            field=models.ForeignKey(help_text='Кейс, для которого сгенерирован документ.', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='cases.case'),
        ),
        migrations.AlterField(
            model_name='generateddocument',
            name='content',
            field=models.TextField(blank=True, help_text='Текст документа (Markdown или обычный текст).'),
        ),
        migrations.AlterField(
            model_name='generateddocument',
            name='doc_type',
            field=models.CharField(choices=[('vision', 'Vision / Product Vision'), ('scope', 'Scope')], help_text='Тип документа (vision, scope, use_case и т.д.).', max_length=50),
        ),
        migrations.AlterField(
            model_name='generateddocument',
            name='error_message',
            field=models.TextField(blank=True, help_text='Сообщение об ошибке при генерации, если была.', null=True),
        ),
        migrations.AlterField(
            model_name='generateddocument',
            name='generation_status',
            field=models.CharField(choices=[('new', 'New'), ('generating', 'Generating'), ('ready', 'Ready'), ('failed', 'Failed')], default='new', help_text='Статус генерации (new/generating/ready/failed).', max_length=50),
        ),
        migrations.AlterField(
            model_name='generateddocument',
            name='llm_model',
            field=models.CharField(blank=True, help_text='Название модели, которая сгенерировала документ (например, gpt-4.1-mini).', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='generateddocument',
            name='prompt_hash',
            field=models.CharField(blank=True, help_text='Хеш system+user промпта для определения устаревания.', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='generateddocument',
            name='prompt_version',
            field=models.CharField(blank=True, help_text='Версия промпта для этого типа документа.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='generateddocument',
            name='source_snapshot_hash',
            field=models.CharField(blank=True, help_text='Хеш исходных данных кейса (initial_answers + followups), на базе которых генерился документ.', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='generateddocument',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('approved_by_ba', 'Approved by BA'), ('rejected_by_ba', 'Rejected by BA')], default='draft', help_text='Статус документа (draft/approved/rejected).', max_length=50),
        ),
        migrations.AlterField(
            model_name='generateddocument',
            name='structured_data',
            field=models.JSONField(blank=True, help_text='Структурированное представление документа (JSON), для доработок и экспорта.', null=True),
        ),
        migrations.AlterField(
            model_name='generateddocument',
            name='title',
            field=models.CharField(help_text='Заголовок документа (может быть сгенерирован из кейса).', max_length=255),
        ),
    ]
