# Generated by Django 5.2.8 on 2025-11-27 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_alter_case_status_followupquestion'),
        ('documents', '0007_generateddocument_docx_file_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generateddocument',
            options={'ordering': ['case', 'doc_type', 'created_at'], 'verbose_name': 'Generated document', 'verbose_name_plural': 'Generated documents'},
        ),
        migrations.AlterUniqueTogether(
            name='generateddocument',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='generateddocument',
            name='diagram_file',
            field=models.FileField(blank=True, help_text='Файл с картинкой диаграммы (PNG), полученной из PlantUML.', null=True, upload_to='generated_diagrams/'),
        ),
        migrations.AlterField(
            model_name='generateddocument',
            name='case',
            field=models.ForeignKey(help_text='Кейс, для которого сгенерирован документ/диаграмма.', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='cases.case'),
        ),
        migrations.AlterField(
            model_name='generateddocument',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='generateddocument',
            name='doc_type',
            field=models.CharField(choices=[('vision', 'Vision / Product Vision'), ('scope', 'Scope / Product Scope'), ('bpmn', 'BPMN Diagram')], help_text='Тип документа (vision, scope, bpmn и т.д.).', max_length=50),
        ),
        migrations.AlterField(
            model_name='generateddocument',
            name='docx_file',
            field=models.FileField(blank=True, help_text='DOCX-версия документа (для текстовых документов).', null=True, upload_to='generated_docs/'),
        ),
        migrations.AlterField(
            model_name='generateddocument',
            name='docx_generated_at',
            field=models.DateTimeField(blank=True, help_text='Когда последний раз генерировался DOCX.', null=True),
        ),
        migrations.AlterField(
            model_name='generateddocument',
            name='error_message',
            field=models.TextField(blank=True, help_text='Текст ошибки генерации, если что-то пошло не так.', null=True),
        ),
        migrations.AlterField(
            model_name='generateddocument',
            name='generation_status',
            field=models.CharField(choices=[('new', 'New'), ('generating', 'Generating'), ('ready', 'Ready'), ('failed', 'Failed')], default='new', max_length=50),
        ),
        migrations.AlterField(
            model_name='generateddocument',
            name='llm_model',
            field=models.CharField(blank=True, help_text='Имя модели, которая генерировала документ.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='generateddocument',
            name='prompt_hash',
            field=models.CharField(blank=True, help_text='Хэш system+user промпта для определения устаревания.', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='generateddocument',
            name='prompt_version',
            field=models.CharField(blank=True, help_text='Версия промпта для этого документа.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='generateddocument',
            name='source_snapshot_hash',
            field=models.CharField(blank=True, help_text='Хэш кейса/ответов, на основе которых был сгенерен документ.', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='generateddocument',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('approved_by_ba', 'Approved by BA'), ('rejected_by_ba', 'Rejected by BA')], default='draft', max_length=50),
        ),
        migrations.AlterField(
            model_name='generateddocument',
            name='structured_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generateddocument',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
