# Generated by Django 5.2.8 on 2025-11-27 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_alter_generateddocument_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generateddocument',
            name='diagram_file',
        ),
        migrations.AddField(
            model_name='generateddocument',
            name='diagram_url',
            field=models.URLField(blank=True, help_text='External PlantUML server image URL for diagram-like documents.', null=True),
        ),
    ]
