# Generated by Django 5.2.8 on 2025-11-27 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_remove_generateddocument_diagram_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generateddocument',
            name='diagram_url',
            field=models.URLField(blank=True, help_text='Ссылка на картинку диаграммы (PNG) на PlantUML-сервере.', null=True),
        ),
        migrations.AlterField(
            model_name='generateddocument',
            name='doc_type',
            field=models.CharField(choices=[('vision', 'Vision / Product Vision'), ('scope', 'Scope / Product Scope'), ('bpmn', 'BPMN Diagram'), ('context_diagram', 'Context Diagram')], help_text='Тип документа (vision, scope, bpmn, context_diagram и т.д.).', max_length=50),
        ),
    ]
